### ISSUE TITLE
The LevenshteinFS module returns values larger than the maximum score

### ISSUE THREAD

**Issue by ChrisTheBaron** [unlooped/FuzzySearchJS#2]
``` javascript
var sentences = [
			'the fox and the dog and cat'
		];

var input =
	'the fox and the dog and cat';

var fuzzySearch = new FuzzySearch(sentences, {
	'caseSensitive': false,
	'returnEmptyArray': true
});

fuzzySearch.addModule(LevenshteinFS({'maxDistanceTolerance': 3, 'factor': 1}));

var results = fuzzySearch.search(input);

console.log(fuzzySearch.getMaximumScore());

console.log(results);
```
Outputs the following:
``` bash
100
[ { score: 433.3333333333333,
    details: [ [Object] ],
    value: 'the fox and the dog and cat' } ]
```

**Comment by n3o77** [comment]
Interesting. I'll have a closer look later tonight. Thanks for reporting!

**Comment by ChrisTheBaron** [comment]
Hey,

Have you had a chance to take a look at it? 
I'm happy to try to fix it myself and submit a PR if you want?

Cheers, Chris

**Comment by n3o77** [comment]
Sorry I hadn't the time to fix it. A pull request is always welcome!

**Comment by ChrisTheBaron** [comment]
Hey,

I've taken a look at the code in the LevenshteinFS module and it seems to be doing more than just calculate the distance between the two string. Am I correct in thinking it takes account of the distances between combinations of words regardless of their position in the string? And if so, what would be the reason for doing this?

Cheers, Chris

**Comment by n3o77** [comment]
Yes you're right. I'm parsing each word and not the whole sentence. that's because you would like to get a relatively good result for "the fox and the cat and dog" but just a slightly better result for "the fox and the dog and cat". If you don't consider each word and just compare the whole sentence it's really possible that you don't get a match at all for this sentence because your max distance tolerance is way off.

But maybe this should be an option because I could imagine that there are some cases where you don't want to have such a behavior.

Best,
Steffen

**Comment by ChrisTheBaron** [comment]
Well it looks like the IndexOfFS module would return a high result for "the fox and the cat and dog" because it's all of the words but not in the correct order. The LevenshteinFS module could be made to only look for misspellings in words/sentences. Would the modules still work together if the LevenshteinFS module didn't have the option for max distance? 

Cheers, Chris

**Comment by n3o77** [comment]
If I am seeing the issue correctly I guess the "50 /" doesn't make any sense (no idea why i did that, wrote this 2 years ago, sorry) and it also doesn't take the word count into account properly which should explain why the score is so far off. Sadly earliest i can take a closer look at that is over the weekend.

Your suggestion doesn't sound wrong to me.

**Comment by ChrisTheBaron** [comment]
Hey,

No worries, it happens to all of us. I'm in no rush to get the issue sorted so if you want to take a look at it  whenever you can then I'll wait.

What could be done is split it into two modules, a simple one and a more advanced one. This would allow you to develop it further as it does sound like a cool idea.

Cheers, Chris

**Comment by n3o77** [comment]
Alright. Like I said, i don't mind a pull request at all, it's very welcome and I appreciate the input.

If you don't get it sorted out i'll take some time on the weekend :)

**Comment by frogamic** [comment]
The reason that the LevenshteinFS module can exceed the max score is that you allow repeated matches between needle words and haystack words.
In the case of **the fox and the dog and cat** every single permutation will match since the words are all `maxDistanceTolerance` in length.
To avoid this you can limit the matches to only the best needle word for each haystack word, I've made some changes and I'll submit a pull request shortly.
